Skip to content
IvanZammarrelli
/
github-secrets

Type / to search

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
CI/CD Pipeline
Update 3main.yml #5
Jobs
Run details
Workflow file for this run
.github/workflows/2main.yml at 641d47e
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Use API Key
      run: echo "SECRET_API_KEY=${{ secrets.SECRET_API_KEY }}" >> $GITHUB_ENV
Update 3main.yml · IvanZammarrelli/github-secrets@641d47e 
